# Site Settings
title: The Games Archive by yEAh
email: admin@yeahgames.net
description: Play, discover, learn, and build yEAh Games online. This is the yEAh library collection for games.
baseurl: ""
url: "https://gamesarchive.yeahgames.net" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: yeahgames
user_description: Official archive publications.

# Social Media
# Remove the item if you don't need it
github_username: yeah-games
twitter_username: yeahgames_
instagram_username: _yeahgames

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
